"""empty message

Revision ID: 96d384e39901
Revises: 
Create Date: 2024-04-20 17:01:44.796841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d384e39901'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto',
    sa.Column('draw_round', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('first_winner_amount', sa.Integer(), nullable=False),
    sa.Column('first_winner_count', sa.Integer(), nullable=False),
    sa.Column('first_total_amount', sa.Integer(), nullable=False),
    sa.Column('draw_number1', sa.Integer(), nullable=False),
    sa.Column('draw_number2', sa.Integer(), nullable=False),
    sa.Column('draw_number3', sa.Integer(), nullable=False),
    sa.Column('draw_number4', sa.Integer(), nullable=False),
    sa.Column('draw_number5', sa.Integer(), nullable=False),
    sa.Column('draw_number6', sa.Integer(), nullable=False),
    sa.Column('bonus_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('draw_round')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotto')
    # ### end Alembic commands ###
